### ISSUE TITLE
running a simple program with zeromq 4.0.5 results in a segfault

### ISSUE THREAD

**Issue by manasapte** [zeromq/jzmq#373]
I built jzmq from the latest master today by following the instructions in the readme like:

```
./autogen.sh
./configure
make 
make install
```

and I see this in my /usr/local/lib:

```
wonderbox:~ manasapte$ ls -al /usr/local/lib/* | grep mq
-rwxr-xr-x  1 manasapte  admin   30836 Feb 28 12:22 /usr/local/lib/libjzmq.0.dylib
-rw-r--r--  1 manasapte  admin  371792 Feb 28 12:22 /usr/local/lib/libjzmq.a
lrwxr-xr-x  1 manasapte  admin      15 Feb 28 12:22 /usr/local/lib/libjzmq.dylib -> libjzmq.0.dylib
-rwxr-xr-x  1 manasapte  admin     954 Feb 28 12:22 /usr/local/lib/libjzmq.la
lrwxr-xr-x  1 manasapte  admin      43 Nov 29 15:23 /usr/local/lib/libzmq.4.dylib -> ../Cellar/zeromq/4.0.5_2/lib/libzmq.4.dylib
lrwxr-xr-x  1 manasapte  admin      37 Nov 29 15:23 /usr/local/lib/libzmq.a -> ../Cellar/zeromq/4.0.5_2/lib/libzmq.a
lrwxr-xr-x  1 manasapte  admin      41 Nov 29 15:23 /usr/local/lib/libzmq.dylib -> ../Cellar/zeromq/4.0.5_2/lib/libzmq.dylib
lrwxr-xr-x   1 manasapte  admin    51 Nov 29 15:23 libzmq.pc -> ../../Cellar/zeromq/4.0.5_2/lib/pkgconfig/libzmq.pc
```

You can also see the version of libzmq, which is installed using homebrew:

```
wonderbox:~ manasapte$ brew info zeromq
zeromq: stable 4.0.5 (bottled), HEAD
http://www.zeromq.org/
/usr/local/Cellar/zeromq/4.0.5_2 (64 files, 2.8M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/zeromq.rb
```

I am on OS X yosemite 10.10.2 and I am running the following simple program:

```java
package zmq;
import org.zeromq.*;
public class TestZmq {
	public static void main(String[] args) throws InterruptedException {
		ZMQ.Context ctx = ZMQ.context(1);
		ZMQ.Socket sock = ctx.socket(ZMQ.ROUTER);
		sock.bind("ipc:///Users/manasapte/snapshot.sock");
		while(true) {
			Thread.sleep(1000);
		}
	}
}
```

I am using the native zeromq library, this is an excerpt from my pom file:
```
<dependency>
  		<groupId>org.zeromq</groupId>
  		<artifactId>jzmq</artifactId>
  		<version>2.1.2</version>
</dependency>
```

When I run the program with -Djava.library.path=/usr/local/bin, it segfaults with the following message:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011b4beee8, pid=15958, tid=4867
#
# JRE version: Java(TM) SE Runtime Environment (7.0_45-b18) (build 1.7.0_45-b18)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.45-b08 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libzmq.4.dylib+0x19ee8]  zmq::socket_base_t::check_tag()+0x4
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/manasapte/Lab/workspace/zmq/hs_err_pid15958.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Can someone help me fix this? Has anyone faced this issue?

**Comment by trevorbernard** [comment]
Your library path should be /usr/local/lib and not bin. See if that changes anything. Also the version of JZMQ is very old; the latest version is 3.1.0. If the problem persists try adding this to your java process to get more info:

    -Xcheck:jni

**Comment by manasapte** [comment]
@trevorbernard sorry, it was a mistake, my library path is /usr/local/lib not bin. I am getting this error with the correct library path. Let me see what I get with -Xcheck:jni

**Comment by manasapte** [comment]
this is what I see with -Xcheck:jni option enabled
FATAL ERROR in native method: Static field ID passed to JNI
	at org.zeromq.ZMQ$Socket.construct(Native Method)
	at org.zeromq.ZMQ$Socket.<init>(ZMQ.java:1336)
	at org.zeromq.ZMQ$Context.socket(ZMQ.java:359)
	at zmq.TestZmq.main(TestZmq.java:6)

**Comment by manasapte** [comment]
also, @trevorbernard what do you mean by the version of jzmq is too old? I cloned the master and built it from source it should build the latest version, how can it be too old?

**Comment by manasapte** [comment]
@trevorbernard it was the version of jzmq, upgraded to 3.1.0 and it worked! Thanks a lot, closing this.
